path_classifiers:
  library:
    - exclude: /
extraction:
  # Provide build configuration for the C files.
  cpp:
    prepare:
      packages:
        - g++
    after_prepare:
        - export CFLAGS='-Isource/include -Wall -Wextra -Werror -Wformat -Wformat-security -Warray-bounds -DSNTP_DO_NOT_USE_CUSTOM_CONFIG'
    index:
      build_command:
        - g++ $CFLAGS -c source/core_sntp_client.c source/core_sntp_serializer.c

  csharp:
    after_prepare:
      - false
  go:
    after_prepare:
      - false
  java:
    after_prepare:
      - false
  javascript:
    after_prepare:
      - false
  python:
    after_prepare:
      - false
